Document: mxser
Title: Debian mxser Manual
Author: <insert document author here>
Abstract: This manual describes what mxser is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mxser/mxser.sgml.gz

Format: postscript
Files: /usr/share/doc/mxser/mxser.ps.gz

Format: text
Files: /usr/share/doc/mxser/mxser.text.gz

Format: HTML
Index: /usr/share/doc/mxser/html/index.html
Files: /usr/share/doc/mxser/html/*.html
